[versions]

# libraries
androidxActivityVersion = "1.12.2"
androidxAppcompatVersion = "1.7.1"
androidxConstraintlayoutVersion = "2.2.1"
androidxCoreVersion = "1.17.0"
androidxFragmentVersion = "1.8.9"
androidxLifecycleRuntimeVersion = "2.10.0"
androidxLifecycleViewmodelVersion = "2.10.0"
androidxNavigationFragmentVersion = "2.9.6"
androidxNavigationUiVersion = "2.9.6"
androidxRoomVersion = "2.8.4"
androidxTestEspressoVersion = "3.7.0"
androidxTestJunitVersion = "1.3.0"
googleAndroidMaterialVersion = "1.13.0"
googleCodeGsonVersion = "2.13.2"
googleDaggerHiltVersion = "2.57.2"
googleFirebaseDatabaseVersion = "22.0.1"
jetbrainsKotlinxCoroutinesVersion = "1.10.2"
junitVersion = "4.13.2"

# plugins
androidApplicationPluginVersion = "8.13.2"
googleMobileServicesPluginVersion = "4.4.4"
jetbrainsKotlinPluginVersion = "2.3.0"

[libraries]

androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidxActivityVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompatVersion" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayoutVersion" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreVersion" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragmentVersion" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntimeVersion" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycleViewmodelVersion" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigationFragmentVersion" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigationUiVersion" }
androidx-room = { module = "androidx.room:room-ktx", version.ref = "androidxRoomVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoomVersion" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspressoVersion" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunitVersion" }
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "googleAndroidMaterialVersion" }
google-code-gson = { module = "com.google.code.gson:gson", version.ref = "googleCodeGsonVersion" }
google-dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "googleDaggerHiltVersion" }
google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "googleDaggerHiltVersion" }
google-firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "googleFirebaseDatabaseVersion" }
jetbrains-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "jetbrainsKotlinxCoroutinesVersion" }
junit = { group = "junit", name = "junit", version.ref = "junitVersion" }

[plugins]

android-application-plugin = { id = "com.android.application", version.ref = "androidApplicationPluginVersion" }
google-mobile-services-plugin = { id = "com.google.gms.google-services", version.ref = "googleMobileServicesPluginVersion" }
jetbrains-kotlin-plugin = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlinPluginVersion" }